[tool.poetry]
name = "repl_python3_pythoncodingtest"
version = "0.1.0"
description = ""
authors = ["skyg547 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
req = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
